## Converting coordinates between projections

Here are some made-up coordinates, UTM zone 16N, NAD27 datum:

In [2]:
x = 1796891.94
y = 101128551.19

We'd like to convert them into UTM zone 15N, WGS84 datum.

For a start, those look like they are in feet. Let's convert them:

In [3]:
x *= 0.3048
y *= 0.3048
x, y

(547692.663312, 30823982.402712002)

We will use the [`pyproj`](https://pypi.python.org/pypi/pyproj) project. 

In [4]:
import pyproj as pp

Set up the 'source' and 'target' projections using [EPSG codes](http://spatialreference.org/):

In [23]:
utm16_nad27 = pp.Proj(init='epsg:26716')
utm15_wgs84 = pp.Proj(init='epsg:32615') 

Now we can do the transformation...

In [6]:
new_coords = pp.transform(utm16_nad27,  # From
                          utm15_wgs84,  # To
                          x, y)         # Coordinates

In [7]:
new_coords  # These are in metres!

(633989.9634796401, -9177126.336612783)

## Other formats

The `x` and `y` could also be arrays:

In [8]:
import numpy as np
x = np.array([500000, 550000, 560000])
y = np.array([1600000, 1650000, 1660000])

pp.transform(utm16_nad27,utm15_wgs84, x, y) 

(array([1147639.24836805, 1196558.79719467, 1206342.16627149]),
 array([1608596.47150905, 1660201.86925774, 1670532.61011427]))

If you have an array of (x, y) pairs, there's a quick way to unpack them:

In [10]:
coords = np.array([[500000, 1600000], [550000, 1650000], [560000, 1660000]])

pp.transform(utm16_nad27,utm15_wgs84, *coords.T) 

(array([1147639.24836805, 1196558.79719467, 1206342.16627149]),
 array([1608596.47150905, 1660201.86925774, 1670532.61011427]))

Or you might have a `pandas` DataFrame with `x` and `y` columns:

In [15]:
import pandas as pd

df = pd.DataFrame(coords, columns=['x_UTM16', 'y_UTM16'])
df['Attrib1'] = [123, 456, 789]

In [16]:
df

x        y  Attrib1
0  500000  1600000      123
1  550000  1650000      456
2  560000  1660000      789

In [19]:
df['x_UTM15'], df['y_UTM15'] = pp.transform(utm16_nad27,utm15_wgs84, df.x.values, df.y.values) 

In [20]:
df

x        y  Attrib1       x_UTM15       y_UTM15
0  500000  1600000      123  1.147639e+06  1.608596e+06
1  550000  1650000      456  1.196559e+06  1.660202e+06
2  560000  1660000      789  1.206342e+06  1.670533e+06

In [21]:
pd.options.display.float_format = '{:.0f}'.format

In [22]:
df

x        y  Attrib1  x_UTM15  y_UTM15
0  500000  1600000      123  1147639  1608596
1  550000  1650000      456  1196559  1660202
2  560000  1660000      789  1206342  1670533

<img src="https://avatars1.githubusercontent.com/u/1692321?v=3&s=200" style="float:right;" width="50px" /><p style="color:gray; float:right;">© 2019 <a href="http://www.agilegeoscience.com/">Agile Geoscience</a> — <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY</a> — Have fun!&nbsp;&nbsp;&nbsp;</p>